// Datos de Comimos Acá — generado desde data/lugares-completo.csv
// Coordenadas aproximadas a nivel de barrio/localidad (no es la direccion exacta del local).
// No editar a mano: correr tools/build_data.py despues de tocar el CSV.
window.PLACES = [
  {
    "id": 1,
    "nombre": "Saint Gallen",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 7.9,
    "resena": "Muy buena coctelería y barra recomendable. El lugar está lindo, con una decoración particular que no molesta para disfrutarlo. La atención es excelente. La comida no es mala, pero viene bajando de nivel visita tras visita — al principio estaba mejor que ahora.",
    "visitas": "3",
    "distincion": null,
    "lat": -31.396425,
    "lon": -64.178589
  },
  {
    "id": 2,
    "nombre": "La Capke",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 7.5,
    "nota": 8.6,
    "resena": "Comida muy rica, café de buena calidad. Lugar limpio y ordenado. La atención es lo más flojo: tarda tanto en preparar la mesa como en tomar y traer el pedido.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.396373,
    "lon": -64.178642
  },
  {
    "id": 3,
    "nombre": "Club de la milanesa",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.5,
    "nota": 7.4,
    "resena": "Franquicia previsible: vas, comés una milanesa y listo. Comida normal, sin nada que destacar pero tampoco mal sabor. Lugar un tanto oscuro, en la media. No es un lugar que enamore, pero cumple sin sorprender — podés ir veinte veces y mantiene siempre esa calidad media.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.3958,
    "lon": -64.179922
  },
  {
    "id": 4,
    "nombre": "Pizzería popular",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.1,
    "resena": "Pizza muy rica, gran variedad de opciones — recomendable pedir el borde relleno si lo ofrecen, cambia la experiencia. El lugar está bueno para aprovechar en verano o una noche de primavera sentados afuera. Atención normal, cumple sin ser espectacular.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.396867,
    "lon": -64.178554
  },
  {
    "id": 5,
    "nombre": "Filo street food",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.2,
    "resena": "El concepto de \"comida de calle del mundo\" está muy bien trabajado, comida muy buena aunque le faltó un factor sorpresa para llegar más alto. Conviene comer en la barra: ahí se ve el armado de los pedidos, más disfrutable y fiel a la experiencia callejera (las mesas/sillones son algo incómodas). Atención normal, cumple. Un lugar para volver hasta probar la carta completa.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.395924,
    "lon": -64.178166
  },
  {
    "id": 6,
    "nombre": "Questa milanga",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$",
    "comida": 6.5,
    "lugar": 6.5,
    "atencion": 6.5,
    "nota": 6.5,
    "resena": "Más un bar para tomar una birra que otra cosa. La comida es toda frita/apanada, no da para mucho más que eso. Cumple sin sorprender — un lugar para ir sin reserva y zafar una salida improvisada.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.399149,
    "lon": -64.179685
  },
  {
    "id": 7,
    "nombre": "Lo del armenio",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$",
    "comida": 7.75,
    "lugar": 6.0,
    "atencion": 6.0,
    "nota": 6.9,
    "resena": "Comida rica, quizás algo sobrecondimentada. Un lugar para ir y retirar la comida más que para quedarse: carece de concepto/experiencia, como si hubieran puesto unas mesas y no mucho más. El local no es feo, pero está demasiado liso y blanco, tipo local a estrenar.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.397264,
    "lon": -64.177867
  },
  {
    "id": 8,
    "nombre": "Pizza Zeta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.0,
    "nota": 7.2,
    "resena": "Pizza muy rica. Al igual que Questa milanga, es un lugar al que se va de improvisado. Cumple sin sorprender.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.396345,
    "lon": -64.177169
  },
  {
    "id": 9,
    "nombre": "San Pietro",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 9.0,
    "resena": "El mejor lugar de Córdoba. La comida es espectacular, no decepcionó ni una vez — sorprende cada vez que van. Lugar y atención a la altura. Para ir cada vez que se pueda. Recomiendan siempre pedir pastas.",
    "visitas": "3",
    "distincion": null,
    "lat": -31.39841,
    "lon": -64.180378
  },
  {
    "id": 10,
    "nombre": "Ribeca",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.0,
    "atencion": 7.0,
    "nota": 7.4,
    "resena": "Al igual que Questa milanga y Pizza Zeta: cumple pero no sorprende.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.39619,
    "lon": -64.181059
  },
  {
    "id": 11,
    "nombre": "Pizza Bocatana",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 8.0,
    "resena": "Muy buena pizza, sólida. El lugar está bueno pero adentro se hace un poco chico — conviene ir en verano o primavera para estar afuera. Atención normal. Volverían por la pizza y unas birras: recomendable para cortar la semana con una cena al lado del río.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.397921,
    "lon": -64.177697
  },
  {
    "id": 12,
    "nombre": "El Patio de los Naranjos",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Gral Paz",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 8.5,
    "resena": "Un bodegón con preparación a la vista. La carta ofrece dos menús de tapeo que suelen cambiar cada dos meses — conviene ir de a dos y pedir uno de cada uno para probar todo y compartir. Lugar y atención muy cálidos. Comida muy rica.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.396468,
    "lon": -64.179351
  },
  {
    "id": 13,
    "nombre": "Ochre",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 6.0,
    "lugar": 6.0,
    "atencion": 5.0,
    "nota": 5.8,
    "resena": "Cuando se llamaba Ochre (ahora cambió de nombre): un lugar al que no volverían. Comida olvidable, atención medio pelo tirando a mala (complican la forma de pago), lugar sin nada que lo destaque. Precios completamente sobrevalorados — por esa misma plata se puede comer dos veces en cualquier otro lugar de la zona y mejor en todo.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.36392,
    "lon": -64.193982
  },
  {
    "id": 14,
    "nombre": "ES tostadores",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.5,
    "atencion": 8.5,
    "nota": 8.6,
    "resena": "Un lugar para amantes del café. Fueron por la comida y el café terminó deslumbrando — todo marida perfecto, manejan muy bien los sabores. Comida espectacular, café muy rico, lugar y atención también muy bien. Para volver las veces que haga falta.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.364333,
    "lon": -64.196457
  },
  {
    "id": 15,
    "nombre": "La Mona museo-bar",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 9.0,
    "atencion": 8.25,
    "nota": 8.6,
    "resena": "Bar muy lindo para ir a tomar unos buenos tragos, probar unos lomitos mientras suena la música popular del cuartetero más grande del país. Comida y coctelería muy ricas. El lugar tiene una ambientación espectacular, con detalles por todos lados. Atención buena-normal.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.364563,
    "lon": -64.193244
  },
  {
    "id": 16,
    "nombre": "Chetapys",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 8.0,
    "resena": "De los mejores lomitos de Córdoba, tal vez el mejor de la ciudad. El lugar parece (y es) de otra época: los platos y bandejas de chapa llevan a un tiempo donde el sabor importaba más que nada.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.363886,
    "lon": -64.196521
  },
  {
    "id": 17,
    "nombre": "De a deveras",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.75,
    "atencion": 7.5,
    "nota": 7.7,
    "resena": "Vale la pena, la comida parece mejor que la de otras cafeterías. La sucursal del Paseo de las Rosas es muy linda para ir un sábado por la mañana y desayunar al aire libre.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.365235,
    "lon": -64.193849
  },
  {
    "id": 18,
    "nombre": "Pizzería popular",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.1,
    "resena": "Misma cadena que la de Gral Paz: pizza muy rica, gran variedad de opciones, recomendable pedir el borde relleno si lo ofrecen. Atención normal, cumple sin ser espectacular.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.365261,
    "lon": -64.195666
  },
  {
    "id": 19,
    "nombre": "Valdes",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.25,
    "atencion": 8.25,
    "nota": 8.5,
    "resena": "El mejor lugar de mariscos de Córdoba. El salmón es una cosa de locos. Es caro, pero vale la pena considerando que están comiendo mariscos y pescado en el medio de la ciudad.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.366515,
    "lon": -64.194601
  },
  {
    "id": 20,
    "nombre": "Santa calma",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Parque Sarmiento",
    "momento": "Almuerzo",
    "precio": "$$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.25,
    "nota": 8.5,
    "resena": "El lugar es hermoso, la ubicación en el parque es espectacular. Recomendable ir y comer afuera en una tarde de verano o primavera.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.42541,
    "lon": -64.180384
  },
  {
    "id": 21,
    "nombre": "Abeja Negra",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Parque Sarmiento",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "Cumple sin sorprender demasiado. Lugar lindo, bueno para ir de improviso: suele tener disponibilidad sin reserva y los precios son acordes. Suelen tener promo de cerveza, lo que lo hace recomendable para ir en grupo.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.426857,
    "lon": -64.178673
  },
  {
    "id": 22,
    "nombre": "El bosque",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Parque Sarmiento",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "Igual que Abeja Negra: cumple sin sorprender demasiado. Lugar lindo, bueno para ir de improviso, con disponibilidad sin reserva y precios acordes.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.424943,
    "lon": -64.177011
  },
  {
    "id": 23,
    "nombre": "Pan Plano",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "Igual que Abeja Negra y El bosque: cumple sin sorprender demasiado. Lugar lindo, bueno para ir de improviso, con disponibilidad sin reserva y precios acordes.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.385034,
    "lon": -64.19768
  },
  {
    "id": 24,
    "nombre": "Panadería Moreno",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Desayuno",
    "precio": "$$",
    "comida": 7.0,
    "lugar": 7.0,
    "atencion": 7.0,
    "nota": 7.0,
    "resena": "Panadería de barrio que ofrece desayunos y meriendas. No es \"guau\", pero el menú cumple a un precio más que económico: tostadas normales, untables comunes y un café rico, con atención normal. No tiene nada que envidiarle a otros lugares de meriendas.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.385401,
    "lon": -64.1985
  },
  {
    "id": 25,
    "nombre": "Montagú",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 7.0,
    "atencion": 7.5,
    "nota": 8.0,
    "resena": "De los mejores lomitos de Córdoba, no falla nunca: muy rico y llenador. Pero es algo caro comparado con cualquier otro lomito de la ciudad.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.383679,
    "lon": -64.19759
  },
  {
    "id": 26,
    "nombre": "Le Marine",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 6.75,
    "lugar": 6.5,
    "atencion": 7.0,
    "nota": 6.8,
    "resena": "Cambió de nombre. La comida es muy normalita para lo caro que resultan los precios.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.384674,
    "lon": -64.198681
  },
  {
    "id": 27,
    "nombre": "Milá",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 6.0,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 6.8,
    "resena": "El lugar es lindo y atienden bien, pero la comida no tiene sabor — casi insípida, algo rarísimo. Por lejos la peor provoleta que probaron hasta ahora: sabor a nada.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.385855,
    "lon": -64.195997
  },
  {
    "id": 28,
    "nombre": "Glotón",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 7.0,
    "lugar": 7.5,
    "atencion": 7.0,
    "nota": 7.1,
    "resena": "Una experiencia demasiado chata para el precio. El local cerró hace poco — eso dice bastante.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.385089,
    "lon": -64.197034
  },
  {
    "id": 29,
    "nombre": "Galo wines",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 8.9,
    "resena": "Visitado un día de los enamorados: tenían un menú especial de pasos, todo riquísimo (aunque algo cuestionable la vajilla). Superador a la comida fue la atención y el lugar: muy prolijo, \"fancy\", y el sistema de autoservicio del vino es bárbaro.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.384171,
    "lon": -64.196843
  },
  {
    "id": 30,
    "nombre": "Alma zen",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 8.5,
    "atencion": 7.5,
    "nota": 8.5,
    "resena": "Comida increíble, con una presentación tremenda. Para los fans del dulce, 100%.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.385086,
    "lon": -64.197265
  },
  {
    "id": 31,
    "nombre": "Maria antonieta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.7,
    "resena": "Café excelente y porciones abundantes.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.382878,
    "lon": -64.195589
  },
  {
    "id": 32,
    "nombre": "Shiok",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 8.75,
    "atencion": 8.0,
    "nota": 8.7,
    "resena": "Las cookies están zarpadas. El café es exquisito.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.384347,
    "lon": -64.195678
  },
  {
    "id": 33,
    "nombre": "Marga Restaurante",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.0,
    "atencion": 8.5,
    "nota": 8.1,
    "resena": "Como ir a comer a la casa de unos tíos. Rica provoleta, quizás top 5. Las pastas son increíbles. Presentación muy linda y un sabor casero zarpado.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.385522,
    "lon": -64.196284
  },
  {
    "id": 34,
    "nombre": "Don Rogelio",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Rogelio Martinez",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.9,
    "resena": "Un clásico de la zona, ambiente familiar. Ideal para ir a comer al mediodía en otoño, en las mesas de afuera al sol. Comida rica pero no sorprende — cumple siempre.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.353447,
    "lon": -64.233134
  },
  {
    "id": 35,
    "nombre": "Tucson",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Rogelio Martinez",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.2,
    "resena": "La comida es rica, pero no lo suficiente para el precio que tienen. ¿Está bueno? Sí. ¿Lo vale? No sé.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.356559,
    "lon": -64.236821
  },
  {
    "id": 36,
    "nombre": "El Celta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "momento": "Almuerzo",
    "precio": "$$$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.75,
    "nota": 7.4,
    "resena": "Un poco quedado en el tiempo: es un clásico, pero se sintió viejo y algo arcaico. La comida está buena sin deslumbrar, y el precio no se corresponde.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.391297,
    "lon": -64.177238
  },
  {
    "id": 37,
    "nombre": "Perón Perón",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 6.75,
    "atencion": 6.5,
    "nota": 7.1,
    "resena": "Normal y accesible. La comida no es guau, pero las porciones son generosas para el precio. El lugar está un poco descuidado, y la atención estuvo complicada.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.38911,
    "lon": -64.179003
  },
  {
    "id": 38,
    "nombre": "Primo",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 7.6,
    "resena": "La tabla es completa y llenadora. Todo tiene medio el mismo sabor, pero va. Los langostinos y camarones son lo mejor para pedir.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.389115,
    "lon": -64.178589
  },
  {
    "id": 39,
    "nombre": "Burgueses",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "momento": "Cena",
    "precio": "$$",
    "comida": 8.75,
    "lugar": 6.0,
    "atencion": 8.0,
    "nota": 7.9,
    "resena": "Es para ir y retirar. Las hamburguesas están buenísimas, y las papas están bárbaras. Súper recomendado.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.388349,
    "lon": -64.177076
  },
  {
    "id": 40,
    "nombre": "Il Forno di Marco",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "momento": "Cena",
    "precio": "$$",
    "comida": 8.75,
    "lugar": 7.75,
    "atencion": 8.5,
    "nota": 8.4,
    "resena": "Un bodegón de pizzas. Atención excelente. La pizza es increíble, de las mejores que comieron en relación precio-calidad.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.388352,
    "lon": -64.180004
  },
  {
    "id": 43,
    "nombre": "Passage du café",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Güemes",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 8.75,
    "atencion": 8.75,
    "nota": 8.9,
    "resena": "El lugar es increíble, la atención lo mismo. Los laminados son bárbaros y el café está zarpado.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.427427,
    "lon": -64.179554
  },
  {
    "id": 45,
    "nombre": "Marvic",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alberdi",
    "momento": "Merienda",
    "precio": "$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 8.3,
    "resena": "Un clásico cordobés, intacto desde que abrió. Se siente noventoso, pero no deja de estar bueno. Tener la plaza al frente hace que siempre esté concurrido, aunque vale la pena ir. Comida muy rica, súper dulce y abundante.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.413604,
    "lon": -64.203713
  },
  {
    "id": 46,
    "nombre": "Clover",
    "provincia": "Córdoba",
    "localidad": "Villa Carlos Paz",
    "barrio": null,
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 9.0,
    "atencion": 8.5,
    "nota": 8.4,
    "resena": "El lugar se lleva todos los aplausos: piso 13 de una torre, con balcones y vista a todo Carlos Paz. La merienda tiene muy buena relación precio-calidad, y la atención es muy buena. Recomiendan reservar.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.422696,
    "lon": -64.496168
  },
  {
    "id": 47,
    "nombre": "Terra Firma",
    "provincia": "Córdoba",
    "localidad": "Villa Carlos Paz",
    "barrio": null,
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.0,
    "nota": 8.4,
    "resena": "El lugar está muy bueno, te sentís medio en \"un castillo\". Comida abundante y sabrosa. La atención tiene sus días, pero en general bien. Recomiendan reservar.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.424479,
    "lon": -64.496576
  },
  {
    "id": 48,
    "nombre": "Bros Comedor",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.25,
    "lugar": 8.75,
    "atencion": 9.0,
    "nota": 9.1,
    "resena": "La comida, por Dios. ¿Es caro? Sí. ¿Vale la pena? Cada centavo.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.420535,
    "lon": -64.187932
  },
  {
    "id": 49,
    "nombre": "Alcorta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "momento": "Cena",
    "precio": "$$",
    "comida": 7.0,
    "lugar": 8.5,
    "atencion": 8.5,
    "nota": 7.75,
    "resena": "Era un clásico. No sabe si la cocina tuvo un mal día, pero cree que hace un mejor asado en su casa. Las porciones eran muy abundantes y súper económicas. El local cerró — se explica solo.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.418282,
    "lon": -64.188146
  },
  {
    "id": 50,
    "nombre": "Marmol",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "El lugar es muy lindo, lo mejor que tiene es la ubicación. Recomendable ir un sábado por la mañana y desayunar ahí.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.419088,
    "lon": -64.190038
  },
  {
    "id": 51,
    "nombre": "Nakama",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 8.75,
    "nota": 8.94,
    "resena": "Les encantó. Comida excelente, y la ambientación del lugar también. Recomiendan reservar con una semana de anticipación mínimo.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.421472,
    "lon": -64.188932
  },
  {
    "id": 52,
    "nombre": "Bar á Vins",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 8.38,
    "resena": "Visitado un día de los enamorados: tenían un menú de pasos muy rico. El lugar es chico, pero no por eso deja de ser lindo.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.419693,
    "lon": -64.189582
  },
  {
    "id": 53,
    "nombre": "De a deveras",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Nueva Córdoba",
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.25,
    "resena": "El lugar suele estar concurrido, por lo que las mesas no abundan. Comida muy rica y atención acorde.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.428322,
    "lon": -64.185499
  },
  {
    "id": 54,
    "nombre": "Lomitería popular",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Nueva Córdoba",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.69,
    "resena": "Lindo lugar en una zona muy concurrida. La comida y las porciones acordes al precio. Bien.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.429098,
    "lon": -64.182284
  },
  {
    "id": 55,
    "nombre": "Hoppiness",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Manantiales",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.5,
    "atencion": 8.5,
    "nota": 8.62,
    "resena": "El mejor lugar de hamburguesas hasta ahora — aunque este último tiempo sufrió \"shrinkflation\", vale la pena seguir yendo. Las hamburguesas son un espectáculo, la birra muy rica y la atención en general no falla.",
    "visitas": "4-5",
    "distincion": null,
    "lat": -31.379168,
    "lon": -64.270332
  },
  {
    "id": 56,
    "nombre": "La sifonda",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Tejas",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.81,
    "resena": "Meh, normal. Una experiencia chata en líneas generales. No destacó en nada, pero aún así cumple.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.35151,
    "lon": -64.246078
  },
  {
    "id": 57,
    "nombre": "El fogón de los arrieros",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Tejas",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 7.0,
    "lugar": 8.0,
    "atencion": 6.5,
    "nota": 7.12,
    "resena": "Cambió de nombre, ya no funciona como El fogón de los arrieros. La comida es medio pelo para el precio. Atención bastante mala (fueron una noche con pocas mesas y no atendían ni de casualidad). El lugar es lindo, pero solo eso. Se entiende que haya cerrado.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.352208,
    "lon": -64.245167
  },
  {
    "id": 58,
    "nombre": "Urban Bakery",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Nuevocentro Shopping",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 7.88,
    "resena": "Lindo lugar, la comida muy \"aesthetic\" y rica. Un poco caro en relación a lo que ofrecen, pero se entiende e igual funciona.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.431392,
    "lon": -64.185138
  },
  {
    "id": 59,
    "nombre": "La Baguala",
    "provincia": "Córdoba",
    "localidad": "La Cumbre",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 9.0,
    "resena": "Excelente lugar. La comida un espectáculo, sabores y presentación muy bien manejados. Personal muy atento y rápido para servir. Recomendado 100%.",
    "visitas": "1",
    "distincion": null,
    "lat": -30.985156,
    "lon": -64.51669
  },
  {
    "id": 60,
    "nombre": "Mirá Silvina",
    "provincia": "Córdoba",
    "localidad": "Salsipuedes",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 8.88,
    "resena": "Hermoso lugar. Ideal para ir en primavera-verano a comer al mediodía bajo la sombra en el patio. Las vistas son hermosas, la atención muy prolija y la comida sabrosa y llenadora.",
    "visitas": "5+",
    "distincion": null,
    "lat": -31.135188,
    "lon": -64.316182
  },
  {
    "id": 61,
    "nombre": "Parador El Cuadrado",
    "provincia": "Córdoba",
    "localidad": "El Cuadrado",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "De los mejores lomitos de Córdoba. El lugar es hermoso, como todo el Camino del Cuadrado en general. Recomendable comer en el patio bajo la sombra. Comida buena, porciones acordes al precio y atención bien también.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.050012,
    "lon": -64.490004
  },
  {
    "id": 62,
    "nombre": "A la vista",
    "provincia": "Córdoba",
    "localidad": "El Cuadrado",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.5,
    "atencion": 9.25,
    "nota": 8.81,
    "resena": "Un lugar familiar: tanto el ambiente como la atención lo hacen sentir como tal. La comida 100% casera es bárbara, desde la entrada hasta los postres. Tienen menú fijo libre para repetir la cantidad de veces que quieras el plato que gustes. Un éxito.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.050922,
    "lon": -64.490978
  },
  {
    "id": 63,
    "nombre": "Pan Plano",
    "provincia": "Córdoba",
    "localidad": "Villa Allende",
    "barrio": null,
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 7.88,
    "resena": "Misma cadena que Pizzería popular y Pan Plano (Jardín): cumple sin sorprender demasiado, un lugar lindo y accesible.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.297242,
    "lon": -64.295574
  },
  {
    "id": 64,
    "nombre": "Macadam",
    "provincia": "Córdoba",
    "localidad": "Colonia Caroya",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.25,
    "lugar": 8.25,
    "atencion": 8.0,
    "nota": 8.19,
    "resena": "Lindo lugar de ambiente familiar.",
    "visitas": "1",
    "distincion": null,
    "lat": -31.165038,
    "lon": -64.084206
  },
  {
    "id": 65,
    "nombre": "La Vaca",
    "provincia": "Córdoba",
    "localidad": "Santa Rosa de Calamuchita",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 7.0,
    "lugar": 7.0,
    "atencion": 6.5,
    "nota": 6.88,
    "resena": "Zafa. No es guau, pero cumple a un precio medianamente acorde a la comida. Ni muy muy ni tan tan.",
    "visitas": "1",
    "distincion": null,
    "lat": -32.064758,
    "lon": -64.533862
  },
  {
    "id": 66,
    "nombre": "Kiddo",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Núñez",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.5,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 8.88,
    "resena": "Sucursal de Núñez. No es para comer en el local, sino retirar y comer en casa. La fila demora 35-40 minutos, pero desde que hacés el pedido hasta que lo recibís no pasan ni 2 minutos — gran servicio. Las hamburguesas son las más ricas que probó, las papas están bárbaras y todo el branding del local es buenísimo. Volvería todas las veces que pueda. Es caro para ser una hamburguesa, pero vale la pena.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.54651,
    "lon": -58.462113
  },
  {
    "id": 67,
    "nombre": "Niño gordo",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.5,
    "lugar": 9.0,
    "atencion": 9.25,
    "nota": 9.31,
    "resena": "Por lejos el mejor lugar en el que ha comido. Los sabores no tienen comparación — no por nada tiene 3 estrellas Michelin. Por supuesto que es carísimo, pero vale cada centavo. La experiencia es sublime, al primer bocado ya se cae la jeta al piso.",
    "visitas": "1",
    "distincion": "3 estrellas Michelin",
    "lat": -34.603898,
    "lon": -58.382248
  },
  {
    "id": 68,
    "nombre": "Confitería Ideal",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Desayuno",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 8.75,
    "nota": 8.81,
    "resena": "Un lugar precioso e icónico de Buenos Aires. Es caro, pero las porciones son muy abundantes, por lo que recomiendan pedir para compartir.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.603138,
    "lon": -58.381377
  },
  {
    "id": 69,
    "nombre": "Banchero",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.94,
    "resena": "Rica pizza porteña. Quizás no la mejor, pero es llenadora y sabrosa. Maridaje con cerveza recomendado.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.605376,
    "lon": -58.383279
  },
  {
    "id": 70,
    "nombre": "Las Cuartetas",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 6.5,
    "atencion": 6.5,
    "nota": 7.75,
    "resena": "En su opinión, la mejor pizzería porteña. La fugazzeta es increíble, nunca probó algo así. El local no es vistoso ni la atención amistosa, pero uno va a estos lugares por la comida — y ahí no falla, sorprende y supera las expectativas. 100% recomendado.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.603751,
    "lon": -58.379903
  },
  {
    "id": 71,
    "nombre": "Cuervo Café",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.75,
    "atencion": 8.0,
    "nota": 7.81,
    "resena": "Lindo lugar, la comida bien y el café muy bueno. Esperaba más, pero sirve.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.602157,
    "lon": -58.382962
  },
  {
    "id": 72,
    "nombre": "La Fernetería",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.25,
    "atencion": 8.0,
    "nota": 8.06,
    "resena": "El lugar es lindo y está bien ambientado. La atención es buena, y la comida, si bien no es \"guau\", es abundante y rica — suele tener ofertas de menú ejecutivo al mediodía. Bien.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.604907,
    "lon": -58.381234
  },
  {
    "id": 73,
    "nombre": "Resto - Museo Eva Perón",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$",
    "comida": 7.75,
    "lugar": 8.25,
    "atencion": 7.75,
    "nota": 7.88,
    "resena": "Una hermosa casona; estar integrado al museo hace de este lugar una experiencia muy linda e interesante. El menú es accesible y abundante. Faltó un poco de sabor a la comida, algo \"chata\" en general, pero cumple y en relación precio-calidad supera.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.602405,
    "lon": -58.37985
  },
  {
    "id": 74,
    "nombre": "La Parolaccia",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 8.88,
    "resena": "Cayeron de rebote en el local y se llevaron una gran experiencia. La atención es increíble, y la comida no se queda atrás.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.602991,
    "lon": -58.382817
  },
  {
    "id": 75,
    "nombre": "Cofi Jaus",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "Igual que Maria antonieta: café excelente y porciones abundantes.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.60244,
    "lon": -58.382528
  },
  {
    "id": 76,
    "nombre": "Güerrin",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.25,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 8.06,
    "resena": "Sin dudas la pizzería más icónica de Buenos Aires. Pagaron el servicio de mesa, pero recomiendan pedir pizza al corte en el horno de la entrada para una experiencia más típica porteña. La pizza está muy buena, con una cantidad absurda de queso, aunque pareció cara para el producto que ofrecen. La atención no es mala, pero se siente que apuran a comer para rotar mesas.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.601765,
    "lon": -58.381986
  },
  {
    "id": 77,
    "nombre": "Ninina",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "Muy lindo lugar, se lo ve limpio y ordenado. La atención es buena. La comida es rica y el café excelente.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.605062,
    "lon": -58.382259
  },
  {
    "id": 78,
    "nombre": "Kim Chino",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 7.5,
    "atencion": 7.0,
    "nota": 7.38,
    "resena": "Meh, cumple.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.604857,
    "lon": -58.382008
  },
  {
    "id": 79,
    "nombre": "Rita",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "Igual que Ninina: muy lindo lugar, se lo ve limpio y ordenado. La atención es buena. La comida es rica y el café excelente.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.602419,
    "lon": -58.383461
  },
  {
    "id": 80,
    "nombre": "Il Ballo del Mattone",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "momento": "Almuerzo",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 8.25,
    "nota": 8.44,
    "resena": "El lugar tiene mucho estilo, una mezcla de bodegón con bar bohemio que funciona. La comida es bárbara, aunque resultó un tanto costosa en relación al tamaño de la porción y los sabores.",
    "visitas": "1",
    "distincion": null,
    "lat": -34.601947,
    "lon": -58.380553
  }
];
