// Datos de Comimos Acá — generado desde data/lugares-completo.csv
// Los lugares marcados como cerrados en el CSV se excluyen de este archivo.
// Coordenadas: exactas cuando la fila tiene 'ubicacion' cargada; si no, aproximadas a nivel de barrio/localidad.
// Fotos: se detectan automáticamente desde images/<id>-<n>.jpg (ver tools/build_data.py).
// No editar a mano: correr tools/build_data.py despues de tocar el CSV o la carpeta images/.
window.PLACES = [
  {
    "id": 1,
    "nombre": "Saint Gallen",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 7.88,
    "resena": "Muy buena coctelería (experiencia en barra recomendable). El lugar está lindo, con una decoración particular. La atención es muy buena. La comida no es mala, pero viene bajando de nivel visita tras visita — antes estaba mejor.",
    "visitas": "3",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/1-1.jpg"
    ],
    "lat": -31.41426,
    "lon": -64.169075
  },
  {
    "id": 2,
    "nombre": "La Capke",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 7.5,
    "nota": 8.63,
    "resena": "Comida muy rica, café de buena calidad. Lugar limpio y ordenado. La atención es lo más flojo; un tanto demorados pero normal para un día con mucha gente.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/2-1.jpg",
      "images/2-2.jpg"
    ],
    "lat": -31.414349,
    "lon": -64.165468
  },
  {
    "id": 3,
    "nombre": "Club de la milanesa",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.5,
    "nota": 7.38,
    "resena": "Es el club de la milanesa: vas, comés una milanesa y listo. La comida bien, normal pero de porciones abundantes. El lugar un tanto oscuro. No es un lugar que enamore, pero cumple. Podés ir veinte veces y mantiene la calidad.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.414391,
    "lon": -64.168698
  },
  {
    "id": 4,
    "nombre": "Pizzería popular",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.13,
    "resena": "Pizza muy rica, gran variedad de opciones — recomendable pedir el borde relleno si lo ofrecen, cambia la experiencia. El lugar está bueno para aprovechar en verano o una noche de primavera sentados afuera. Atención normal.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.416947,
    "lon": -64.169882
  },
  {
    "id": 5,
    "nombre": "Filo street food",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.25,
    "resena": "El concepto de \"comida de calle del mundo\" está muy bien trabajado. Comida muy buena. Conviene comer en la barra: ahí se ve el armado de los pedidos, más disfrutable y fiel a la experiencia callejera (las mesas/sillones son algo incómodas). Atención normal, cumple. Un lugar para volver hasta probar la carta completa.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.418325,
    "lon": -64.170681
  },
  {
    "id": 6,
    "nombre": "Questa milanga",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Bar/Vinoteca",
    "momento": "Cena",
    "precio": "$$",
    "comida": 6.5,
    "lugar": 6.5,
    "atencion": 6.5,
    "nota": 6.5,
    "resena": "Más un bar para tomar una birra que otra cosa. La comida es toda frita/apanada, no da para mucho más que eso. Un lugar para ir sin reserva y zafar una salida improvisada.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.416901,
    "lon": -64.170174
  },
  {
    "id": 7,
    "nombre": "Lo del armenio",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Bodegón",
    "momento": "Cena",
    "precio": "$$",
    "comida": 7.75,
    "lugar": 6.0,
    "atencion": 7.0,
    "nota": 7.13,
    "resena": "Comida rica, quizás algo sobrecondimentada. Un lugar para ir y retirar la comida más que para quedarse: carece de concepto/experiencia, como si hubieran puesto unas mesas y no mucho más. El local no es feo, pero está demasiado liso y blanco, tipo local a estrenar.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.407509,
    "lon": -64.164975
  },
  {
    "id": 8,
    "nombre": "Pizza Zeta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Bodegón",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.0,
    "nota": 7.25,
    "resena": "Pizza muy rica. Debe ser el último \"pizza zeta\" que queda. Atención y lugar bien, normal.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.414719,
    "lon": -64.165442
  },
  {
    "id": 9,
    "nombre": "San Pietro",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 9.0,
    "resena": "El mejor lugar de pastas de Córdoba. La comida es espectacular, no decepcionó ni una vez. Lugar y atención a la altura. Para ir cada vez que se pueda.",
    "visitas": "3",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/9-1.jpg",
      "images/9-2.jpg",
      "images/9-3.jpg",
      "images/9-4.jpg",
      "images/9-5.jpg",
      "images/9-6.jpg"
    ],
    "lat": -31.414871,
    "lon": -64.16424
  },
  {
    "id": 10,
    "nombre": "Ribeca",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.0,
    "atencion": 7.0,
    "nota": 7.38,
    "resena": "Lindo bar para ir a comer algo en verano/primavera para aprovechar la ambientación del patio. La comida es rica sin deslumbrar. Normal.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.415826,
    "lon": -64.17335
  },
  {
    "id": 11,
    "nombre": "Pizza Bocatana",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 8.0,
    "resena": "Muy buena pizza, sólida. El lugar está bueno pero adentro se hace un poco chico — conviene ir en verano o primavera para estar afuera. Atención normal. Hay que ir por la pizza y unas birras: recomendable para cortar la semana con una cena al lado del río.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.41742,
    "lon": -64.172453
  },
  {
    "id": 12,
    "nombre": "El Patio de los Naranjos",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "General Paz",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 8.5,
    "resena": "Un bodegón con preparación a la vista. La carta ofrece dos menús de tapeo que suelen cambiar cada dos meses — conviene ir de a dos y pedir uno de cada uno para probar todo y compartir. Lugar y atención muy cálidos. Comida muy rica.",
    "visitas": "2",
    "distincion": null,
    "recomendado": true,
    "fotos": [],
    "lat": -31.415133,
    "lon": -64.166663
  },
  {
    "id": 15,
    "nombre": "La Mona museo-bar",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "categoria": "Bar/Vinoteca",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 9.0,
    "atencion": 8.25,
    "nota": 8.56,
    "resena": "Bar muy lindo para ir a tomar unos buenos tragos, probar unos lomitos mientras suena la discografía completa del mandamás. Comida y coctelería muy ricas. El lugar tiene una ambientación espectacular, con detalles por todos lados. Atención buena-normal.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.360176,
    "lon": -64.238789
  },
  {
    "id": 16,
    "nombre": "Chetapys",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "categoria": "Bodegón",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 8.0,
    "resena": "De los mejores lomitos de Córdoba (tal vez el mejor para mi gusto). El lugar parece (y es) de otra época: sillas de kiosco, los platos y bandejas de chapa, todo en lo que parece un patio de una casa.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.395673,
    "lon": -64.253612
  },
  {
    "id": 17,
    "nombre": "De a deveras",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.0,
    "nota": 7.75,
    "resena": "Vale la pena, la comida parece mejor que la de otras cafeterías. La sucursal del Paseo de las Rosas es muy linda para ir un sábado por la mañana y desayunar al aire libre.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.360878,
    "lon": -64.236341
  },
  {
    "id": 18,
    "nombre": "Pizzería popular",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.13,
    "resena": "Misma cadena que la de Gral Paz: pizza muy rica, gran variedad de opciones, recomendable pedir el borde relleno si lo ofrecen. Atención normal.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.364742,
    "lon": -64.238277
  },
  {
    "id": 19,
    "nombre": "Valdes",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Zona norte",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.25,
    "atencion": 8.25,
    "nota": 8.5,
    "resena": "El mejor lugar de mariscos de Córdoba. Probamos la tabla (la que trae salmón 100% recomendada). Es caro, pero vale la pena considerando que estás comiendo mariscos y pescado en Córdoba.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/19-1.jpg"
    ],
    "lat": -31.353275,
    "lon": -64.249503
  },
  {
    "id": 20,
    "nombre": "Santa calma",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Parque Sarmiento",
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.25,
    "nota": 8.5,
    "resena": "El lugar es hermoso, la ubicación en el parque es espectacular. Recomendable ir y comer afuera en una tarde de verano o primavera. Hamburguesas/Lomitos recomendados.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.431587,
    "lon": -64.173021
  },
  {
    "id": 21,
    "nombre": "Abeja Negra",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Parque Sarmiento",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.81,
    "resena": "Lugar lindo, bueno para ir de improviso: suele tener disponibilidad sin reserva y los precios son acordes. Suelen tener promo de cerveza, lo que lo hace recomendable para ir en grupo.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.433025,
    "lon": -64.180353
  },
  {
    "id": 22,
    "nombre": "El bosque",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Parque Sarmiento",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "Al igual que todos los ubicados en el parque, resulta ideal para ir al mediodía o una noche de verano para comer afuera. El lomito es bárbaro. La clave esta en pedir uno de lomo y otro de molleja para compartir ambos. Las rabas y camarones son otra gran opción para acompañar con una birra.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.430474,
    "lon": -64.176804
  },
  {
    "id": 23,
    "nombre": "Pan Plano",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "La atención es buena, rápida. La pizza con corazones de alcauciles esta tremenda. Esta bueno para pedir mitad y mitad con una de muzza; y acompañar con cerveza.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/23-1.jpg",
      "images/23-2.jpg"
    ],
    "lat": -31.450275,
    "lon": -64.176476
  },
  {
    "id": 24,
    "nombre": "Panadería Moreno",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.5,
    "nota": 7.38,
    "resena": "Panadería de barrio que ofrece desayunos y meriendas. No es \"guau\", pero el menú cumple a un precio más que económico: tostadas normales, untables comunes y un café rico, con atención normal. No tiene nada que envidiarle a otros lugares de meriendas.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/24-1.jpg"
    ],
    "lat": -31.450644,
    "lon": -64.17875
  },
  {
    "id": 25,
    "nombre": "Montagú",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 7.0,
    "atencion": 7.5,
    "nota": 8.0,
    "resena": "De los mejores lomitos de Córdoba, no falla nunca: muy rico y llenador. Pero es algo caro comparado con otros lomitos.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.448866,
    "lon": -64.182874
  },
  {
    "id": 27,
    "nombre": "Milá",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 6.0,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 6.75,
    "resena": "El lugar es lindo y atienden bien, pero la comida no tiene sabor — casi insípida, algo rarísimo (capaz fue esa vez).",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.451096,
    "lon": -64.177365
  },
  {
    "id": 29,
    "nombre": "Galo wines",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 8.88,
    "resena": "Visitado un día de los enamorados: tenían un menú especial de pasos, todo riquísimo (aunque algo cuestionable la vajilla). Superador a la comida fue la atención y el lugar: muy prolijo, \"fancy\", y el sistema de autoservicio del vino es bárbaro.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/29-1.jpg",
      "images/29-2.jpg",
      "images/29-3.jpg",
      "images/29-4.jpg"
    ],
    "lat": -31.450747,
    "lon": -64.175528
  },
  {
    "id": 30,
    "nombre": "Almazen",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 8.5,
    "atencion": 7.5,
    "nota": 8.5,
    "resena": "Comida increíble, con una presentación tremenda. Para los fans del dulce, 100%.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/30-1.jpg"
    ],
    "lat": -31.45105,
    "lon": -64.175625
  },
  {
    "id": 31,
    "nombre": "Maria antonieta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.69,
    "resena": "Café excelente y porciones abundantes.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.450782,
    "lon": -64.175848
  },
  {
    "id": 32,
    "nombre": "Shiok",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 8.75,
    "atencion": 8.0,
    "nota": 8.69,
    "resena": "Las cookies están zarpadas. El café es exquisito.",
    "visitas": "3",
    "distincion": null,
    "recomendado": true,
    "fotos": [],
    "lat": -31.45098,
    "lon": -64.176836
  },
  {
    "id": 33,
    "nombre": "Marga Restaurante",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Jardín",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.25,
    "atencion": 8.25,
    "nota": 8.13,
    "resena": "Como ir a comer a la casa de unos tíos. Rica provoleta, quizás top 5 de todas las que probamos. Las pastas son increíbles. Presentación muy linda y un sabor casero zarpado.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/33-1.jpg",
      "images/33-2.jpg",
      "images/33-3.jpg"
    ],
    "lat": -31.448628,
    "lon": -64.183197
  },
  {
    "id": 34,
    "nombre": "Don Rogelio",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Rogelio Martinez",
    "categoria": "Bodegón",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.94,
    "resena": "Un clásico de la zona, ambiente familiar. Ideal para ir a comer al mediodía en otoño, en las mesas de afuera al sol.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/34-1.jpg"
    ],
    "lat": -31.436752,
    "lon": -64.178435
  },
  {
    "id": 35,
    "nombre": "Tucson",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Rogelio Martinez",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 7.5,
    "nota": 8.25,
    "resena": "La comida es rica, pero no lo suficiente para el precio que tienen. ¿Está bueno? Sí. ¿Lo vale? No sé.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/35-1.jpg",
      "images/35-2.jpg"
    ],
    "lat": -31.434727,
    "lon": -64.177759
  },
  {
    "id": 36,
    "nombre": "El Celta",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "categoria": "Fancy",
    "momento": "Almuerzo",
    "precio": "$$$$",
    "comida": 7.5,
    "lugar": 7.0,
    "atencion": 7.75,
    "nota": 7.44,
    "resena": "Un poco quedado en el tiempo: es un clásico, pero se sintió viejo y algo arcaico. La comida está buena sin deslumbrar, y el precio no se corresponde.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.398485,
    "lon": -64.180631
  },
  {
    "id": 37,
    "nombre": "Perón Perón",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "categoria": "Bodegón",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 6.75,
    "atencion": 6.5,
    "nota": 7.06,
    "resena": "Normal y accesible. La comida no es guau, pero las porciones son generosas para el precio. El lugar está un poco descuidado, y la atención estuvo complicada.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.39118,
    "lon": -64.183033
  },
  {
    "id": 38,
    "nombre": "Primo",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.5,
    "atencion": 7.5,
    "nota": 7.63,
    "resena": "La tabla es completa y llenadora. Todo tiene medio el mismo sabor (debe ser por el apanado y la fritura), pero viaja. Los langostinos y camarones son lo mejor de la tabla.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/38-1.jpg"
    ],
    "lat": -31.392118,
    "lon": -64.185996
  },
  {
    "id": 39,
    "nombre": "Burgueses",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "categoria": "Comida rápida",
    "momento": "Cena",
    "precio": "$$",
    "comida": 8.75,
    "lugar": 6.0,
    "atencion": 8.0,
    "nota": 7.88,
    "resena": "Es para ir y retirar. Las hamburguesas están buenísimas, y las papas están bárbaras. Súper recomendado.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/39-1.jpg"
    ],
    "lat": -31.401003,
    "lon": -64.176694
  },
  {
    "id": 40,
    "nombre": "Il Forno di Marco",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alta Córdoba",
    "categoria": "Bodegón",
    "momento": "Cena",
    "precio": "$$",
    "comida": 8.75,
    "lugar": 7.75,
    "atencion": 8.5,
    "nota": 8.44,
    "resena": "Un bodegón de pizzas. Atención excelente. La pizza es increíble, de las mejores en relación precio-calidad.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/40-1.jpg"
    ],
    "lat": -31.395045,
    "lon": -64.179804
  },
  {
    "id": 43,
    "nombre": "Passage du café",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Güemes",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 9.0,
    "lugar": 8.75,
    "atencion": 8.75,
    "nota": 8.88,
    "resena": "El lugar es increíble, la atención lo mismo. Los laminados son bárbaros y el café está zarpado.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/43-1.jpg"
    ],
    "lat": -31.418613,
    "lon": -64.191215
  },
  {
    "id": 45,
    "nombre": "Marvic",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Alberdi",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 8.31,
    "resena": "Un clásico cordobés, intacto desde que abrió. Se siente noventoso, pero no deja de estar bueno. Tener la plaza al frente hace que siempre esté concurrido, aunque vale la pena ir. Comida muy rica, súper dulce y abundante.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.403728,
    "lon": -64.218769
  },
  {
    "id": 46,
    "nombre": "Clover Up",
    "provincia": "Córdoba",
    "localidad": "Villa Carlos Paz",
    "barrio": null,
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 9.0,
    "atencion": 8.5,
    "nota": 8.38,
    "resena": "El lugar se lleva todos los aplausos: piso 13 de una torre, con balcones y vista a todo Carlos Paz. La merienda tiene muy buena relación precio-calidad, y la atención es muy buena. Es recomendable reservar si vas en horarios concurridos.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [],
    "lat": -31.420066,
    "lon": -64.495977
  },
  {
    "id": 47,
    "nombre": "Terra Firma",
    "provincia": "Córdoba",
    "localidad": "Villa Carlos Paz",
    "barrio": null,
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.0,
    "nota": 8.44,
    "resena": "El lugar está muy bueno, te sentís medio en \"un castillo\". Comida abundante y sabrosa. La atención tiene sus días, pero en general bien. Es recomendable reservar si vas en horarios concurridos (sobre todo fines de semana).",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [],
    "lat": -31.417004,
    "lon": -64.504572
  },
  {
    "id": 48,
    "nombre": "Bros Comedor",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.25,
    "lugar": 8.75,
    "atencion": 9.0,
    "nota": 9.06,
    "resena": "La comida, por Dios que buena que está. ¿Es caro? Carísimo. ¿Vale la pena? Cada centavo.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/48-1.jpg",
      "images/48-2.jpg",
      "images/48-3.jpg",
      "images/48-4.jpg"
    ],
    "lat": -31.414623,
    "lon": -64.192138
  },
  {
    "id": 51,
    "nombre": "Nakama",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 8.75,
    "nota": 8.94,
    "resena": "Nos encantó. Comida excelente, y la ambientación del lugar también. Recomendable reservar con una semana de anticipación, mínimo.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/51-1.jpg",
      "images/51-2.jpg"
    ],
    "lat": -31.417746,
    "lon": -64.190829
  },
  {
    "id": 52,
    "nombre": "Bar á Vins",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Centro",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.75,
    "atencion": 8.5,
    "nota": 8.31,
    "resena": "Visitado un día de los enamorados: tenían un menú de pasos muy rico. El lugar es chico, pero no por eso deja de ser lindo.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/52-1.jpg",
      "images/52-2.jpg",
      "images/52-3.jpg",
      "images/52-4.jpg"
    ],
    "lat": -31.41853,
    "lon": -64.192602
  },
  {
    "id": 53,
    "nombre": "De a deveras",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Nueva Córdoba",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.25,
    "resena": "El lugar suele estar concurrido, por lo que las mesas no abundan. Comida muy rica y atención acorde.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.424606,
    "lon": -64.181709
  },
  {
    "id": 54,
    "nombre": "Lomitería popular",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Nueva Córdoba",
    "categoria": "Familiar",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.81,
    "resena": "Lindo lugar en una zona muy concurrida. La comida y las porciones acordes al precio. Bien.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.423814,
    "lon": -64.186798
  },
  {
    "id": 55,
    "nombre": "Hoppiness",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Manantiales",
    "categoria": "Comida rápida",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.5,
    "atencion": 8.5,
    "nota": 8.63,
    "resena": "El mejor lugar de hamburguesas hasta ahora — aunque este último tiempo sufrió \"shrinkflation\", vale la pena seguir yendo. Las hamburguesas son un espectáculo, la birra muy rica y la atención en general no falla.",
    "visitas": "5",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/55-1.jpg"
    ],
    "lat": -31.455004,
    "lon": -64.237585
  },
  {
    "id": 56,
    "nombre": "Argumento",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Country Jockey Club",
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.5,
    "atencion": 8.0,
    "nota": 8.13,
    "resena": "Lindo lugar para ir al mediodía o tarde en primavera/verano para estar afuera con vista al golf. La comida no es guau, pero cumple y tiene un precio mas que coherente.",
    "visitas": "",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -31.459213,
    "lon": -64.182761
  },
  {
    "id": 57,
    "nombre": "La sifonda",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Tejas del Sur",
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.75,
    "atencion": 7.75,
    "nota": 7.75,
    "resena": "Lindo lugar, atención normal y comida bien. No hay mucho más que comentar. Bien.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/57-1.jpg"
    ],
    "lat": -31.461838,
    "lon": -64.18738
  },
  {
    "id": 60,
    "nombre": "La Baguala",
    "provincia": "Córdoba",
    "localidad": "La Cumbre",
    "barrio": null,
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 9.0,
    "resena": "Excelente lugar. La comida un espectáculo, sabores y presentación muy bien manejados. Personal muy atento y rápido para servir. La provoleta es bárbara, y las pastas son exquisitas (sobre todo los sorrentinos de carne desmechada)",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/60-1.jpg",
      "images/60-2.jpg"
    ],
    "lat": -30.994717,
    "lon": -64.461927
  },
  {
    "id": 61,
    "nombre": "Mirá Silvina",
    "provincia": "Córdoba",
    "localidad": "Salsipuedes",
    "barrio": null,
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.75,
    "nota": 8.63,
    "resena": "Hermoso lugar. Ideal para ir en primavera-verano a comer al mediodía bajo la sombra en el patio. Las vistas son hermosas, la atención muy prolija y la comida sabrosa y llenadora.",
    "visitas": "5+",
    "distincion": null,
    "recomendado": true,
    "fotos": [],
    "lat": -31.155372,
    "lon": -64.287037
  },
  {
    "id": 62,
    "nombre": "Parador El Cuadrado",
    "provincia": "Córdoba",
    "localidad": "El Cuadrado",
    "barrio": null,
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "De los mejores lomitos de Córdoba. El lugar es hermoso, como todo el Camino del Cuadrado en general. Recomendable comer en el patio bajo la sombra. Comida buena, porciones acordes al precio y atención bien también. La provoleta super recomendada.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/62-1.jpg"
    ],
    "lat": -31.121148,
    "lon": -64.333234
  },
  {
    "id": 63,
    "nombre": "A la vista",
    "provincia": "Córdoba",
    "localidad": "El Cuadrado",
    "barrio": null,
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 8.5,
    "atencion": 9.25,
    "nota": 8.81,
    "resena": "Un lugar familiar: tanto el ambiente como la atención lo hacen sentir como tal. La comida 100% casera es bárbara, desde la entrada hasta los postres. Tienen menú fijo libre para repetir la cantidad de veces que quieras el plato que gustes. Un éxito.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/63-1.jpg",
      "images/63-2.jpg",
      "images/63-3.jpg",
      "images/63-4.jpg",
      "images/63-5.jpg",
      "images/63-6.jpg",
      "images/63-7.jpg"
    ],
    "lat": -31.154814,
    "lon": -64.310442
  },
  {
    "id": 66,
    "nombre": "La Vaca",
    "provincia": "Córdoba",
    "localidad": "Santa Rosa de Calamuchita",
    "barrio": null,
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 7.0,
    "lugar": 7.0,
    "atencion": 6.5,
    "nota": 6.88,
    "resena": "Zafa. No es guau, pero cumple a un precio medianamente acorde a la comida. Ni muy muy ni tan tan.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/66-1.jpg"
    ],
    "lat": -32.06925,
    "lon": -64.536986
  },
  {
    "id": 67,
    "nombre": "Kiddo",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Comida rápida",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.5,
    "lugar": 8.0,
    "atencion": 8.5,
    "nota": 8.88,
    "resena": "No es para comer en el local, sino retirar y comer en casa. La fila demora 35-40 minutos, pero desde que hacés el pedido hasta que lo recibís no pasan ni 2 minutos — gran servicio. Las hamburguesas son las más ricas que probamos, las papas están bárbaras y todo el branding del local es buenísimo. Es para volver en cada visita a Buenos Aires. Es caro para ser una hamburguesa, pero vale la pena.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/67-1.jpg"
    ],
    "lat": -34.586765,
    "lon": -58.432591
  },
  {
    "id": 68,
    "nombre": "Niño gordo",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$$",
    "comida": 9.5,
    "lugar": 9.0,
    "atencion": 9.25,
    "nota": 9.31,
    "resena": "Por lejos el mejor lugar al que fuimos. Los sabores no tienen comparación — no por nada tiene 3 estrellas Michelin. Por supuesto que es carísimo, pero vale cada centavo. La experiencia es sublime, al primer bocado ya se cae la jeta al piso.",
    "visitas": "1",
    "distincion": "3 estrellas Michelin",
    "recomendado": true,
    "fotos": [
      "images/68-1.jpg",
      "images/68-2.jpg",
      "images/68-3.jpg",
      "images/68-4.jpg"
    ],
    "lat": -34.58627,
    "lon": -58.429005
  },
  {
    "id": 69,
    "nombre": "Confitería La Ideal",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Centro",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 8.75,
    "nota": 8.81,
    "resena": "Un lugar precioso e icónico de Buenos Aires. Es caro, pero las porciones son muy abundantes, por lo que se puede compartir.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [
      "images/69-1.jpg",
      "images/69-2.jpg",
      "images/69-3.jpg",
      "images/69-4.jpg"
    ],
    "lat": -34.603734,
    "lon": -58.379531
  },
  {
    "id": 70,
    "nombre": "Banchero",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Centro",
    "categoria": "Comida rápida",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 7.94,
    "resena": "Rica pizza porteña. Quizás no la mejor, pero es llenadora y sabrosa. Maridaje con cerveza recomendado.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/70-1.jpg"
    ],
    "lat": -34.603912,
    "lon": -58.38511
  },
  {
    "id": 71,
    "nombre": "Las Cuartetas",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Centro",
    "categoria": "Comida rápida",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 9.0,
    "lugar": 6.5,
    "atencion": 6.5,
    "nota": 7.75,
    "resena": "La mejor pizzería porteña (hasta ahora). La fugazzeta es increíble. El local no es vistoso ni la atención amistosa, pero uno va a estos lugares por la comida — y ahí no falla, sorprende y supera las expectativas. 100% recomendado.",
    "visitas": "1",
    "distincion": null,
    "recomendado": true,
    "fotos": [],
    "lat": -34.603477,
    "lon": -58.378648
  },
  {
    "id": 72,
    "nombre": "Cuervo Café",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 7.75,
    "lugar": 7.75,
    "atencion": 8.0,
    "nota": 7.81,
    "resena": "Lindo lugar, la comida bien y el café muy bueno. Esperaba más, pero sirve.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/72-1.jpg",
      "images/72-2.jpg"
    ],
    "lat": -34.590111,
    "lon": -58.425807
  },
  {
    "id": 73,
    "nombre": "La Fernetería",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": null,
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.25,
    "atencion": 8.0,
    "nota": 8.06,
    "resena": "El lugar es lindo y está bien ambientado. La atención es buena, y la comida, si bien no es \"guau\", es abundante y rica — suele tener ofertas de menú ejecutivo al mediodía. Bien.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/73-1.jpg",
      "images/73-2.jpg"
    ],
    "lat": -34.583319,
    "lon": -58.392525
  },
  {
    "id": 74,
    "nombre": "Resto - Museo Eva Perón",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Bodegón",
    "momento": "Almuerzo",
    "precio": "$$",
    "comida": 7.75,
    "lugar": 8.25,
    "atencion": 7.75,
    "nota": 7.88,
    "resena": "Una hermosa casona; estar integrado al museo hace de este lugar una experiencia muy linda e interesante. El menú es accesible y abundante. Faltó un poco de sabor a la comida, algo \"chata\" en general, pero cumple en relación precio-calidad.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/74-1.jpg",
      "images/74-2.jpg"
    ],
    "lat": -34.580496,
    "lon": -58.414897
  },
  {
    "id": 75,
    "nombre": "La Parolaccia",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Recoleta",
    "categoria": "Fancy",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.75,
    "lugar": 9.0,
    "atencion": 9.0,
    "nota": 8.88,
    "resena": "Caimos de rebote en el local y nos llevamos una gran experiencia. La atención es increíble, y la comida no se queda atrás. Al mediodia tienen un menú ejecutivo muy completo.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/75-1.jpg",
      "images/75-2.jpg",
      "images/75-3.jpg",
      "images/75-4.jpg",
      "images/75-5.jpg"
    ],
    "lat": -34.587934,
    "lon": -58.391054
  },
  {
    "id": 76,
    "nombre": "Cofi Jaus",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.0,
    "lugar": 8.0,
    "atencion": 8.0,
    "nota": 8.0,
    "resena": "Café excelente y porciones abundantes. Gran atención (estabamos solos en el local pero cuenta)",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/76-1.jpg"
    ],
    "lat": -34.584019,
    "lon": -58.434471
  },
  {
    "id": 77,
    "nombre": "Güerrin",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Centro",
    "categoria": "Comida rápida",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 7.75,
    "atencion": 7.5,
    "nota": 8.06,
    "resena": "Sin dudas la pizzería más icónica de Buenos Aires. Pagamos el servicio de mesa, pero es más para pedir pizza al corte en el horno de la entrada para una experiencia más típica porteña. La pizza está muy buena, con una cantidad absurda de queso, aunque nos pareció cara para el producto que ofrecen. La atención no es mala, pero se siente que apuran a comer para rotar mesas.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/77-1.jpg"
    ],
    "lat": -34.603732,
    "lon": -58.386003
  },
  {
    "id": 78,
    "nombre": "Ninina",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "Muy lindo lugar, se lo ve limpio y ordenado. La atención es buena. La comida es rica y el café excelente.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -34.591091,
    "lon": -58.428682
  },
  {
    "id": 79,
    "nombre": "Casa Kim Frito Chino",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Barrio chino",
    "categoria": "Familiar",
    "momento": "Almuerzo",
    "precio": "$$$",
    "comida": 7.5,
    "lugar": 7.5,
    "atencion": 7.0,
    "nota": 7.38,
    "resena": "La comida es buena, pero demoraron mucho para traer los platos. Los dumplings estaban bárbaros.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/79-1.jpg",
      "images/79-2.jpg"
    ],
    "lat": -34.556041,
    "lon": -58.451422
  },
  {
    "id": 80,
    "nombre": "Rita",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo",
    "categoria": "Café/Confitería",
    "momento": "Desayuno",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "Muy lindo lugar. La atención es buena. La comida es rica y el café excelente.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [],
    "lat": -34.589964,
    "lon": -58.428347
  },
  {
    "id": 81,
    "nombre": "Il Ballo del Mattone",
    "provincia": "Buenos Aires",
    "localidad": "Ciudad de Buenos Aires",
    "barrio": "Palermo Hollywood",
    "categoria": "Bodegón",
    "momento": "Almuerzo",
    "precio": "$$$$",
    "comida": 8.75,
    "lugar": 8.0,
    "atencion": 8.25,
    "nota": 8.44,
    "resena": "El lugar tiene mucho estilo, una mezcla de bodegón con bar bohemio que funciona. La comida es bárbara, aunque resultó un tanto costosa en relación al tamaño de la porción y los sabores.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/81-1.jpg",
      "images/81-2.jpg",
      "images/81-3.jpg"
    ],
    "lat": -34.581675,
    "lon": -58.438123
  },
  {
    "id": 82,
    "nombre": "Pituco",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Nueva Córdoba",
    "categoria": "Fancy",
    "momento": "Cena",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.75,
    "atencion": 8.5,
    "nota": 8.56,
    "resena": "Como el nombre indica, es muy \"pituco\" todo. Prolijito, rico y sencillo. La comida es muy rica, de carta acotada pero cumple. Fuerte al medio.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/82-1.jpg",
      "images/82-2.jpg",
      "images/82-3.jpg",
      "images/82-4.jpg",
      "images/82-5.jpg"
    ],
    "lat": -31.426281,
    "lon": -64.188838
  },
  {
    "id": 83,
    "nombre": "Catu pastelería",
    "provincia": "Córdoba",
    "localidad": "Córdoba Capital",
    "barrio": "Cofico",
    "categoria": "Café/Confitería",
    "momento": "Merienda",
    "precio": "$$$",
    "comida": 8.5,
    "lugar": 8.0,
    "atencion": 7.75,
    "nota": 8.19,
    "resena": "El lugar esta bueno, la atención es rápida y tanto la comida como el café muy ricos ambos.",
    "visitas": "1",
    "distincion": null,
    "recomendado": false,
    "fotos": [
      "images/83-1.jpg"
    ],
    "lat": -31.39961,
    "lon": -64.18411
  }
];
